#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Oct 03, 2017 10:19:34 PM
import sys
from DownloadScripts import GoogleMusicDownload
from DownloadScripts import ToDoist
from DownloadScripts import Billboard_Chart_Downloader
from DownloadScripts import no_album_art

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

from tkFileDialog import *
import GUI_Support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.resizable(width=False, height=False)
    GUI_Support.set_Tk_var()
    top = Music_Downloader (root)
    GUI_Support.init(root, top)
    root.mainloop()

w = None

def create_Music_Downloader(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    GUI_Support.set_Tk_var()
    top = Music_Downloader (w)
    GUI_Support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Music_Downloader():
    global w
    w.destroy()
    w = None


class Music_Downloader:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font13 = "-family Arial -size 10 -weight normal -slant roman "  \
            "-underline 0 -overstrike 0"
        font16 = "-family {Segoe UI} -size 8 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 9 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"

#        top.geometry("600x692+650+150")
        top.geometry('{}x{}'.format(600, 500))
        top.title("Music Downloader")
        top.configure(background="#444444")



        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)



        self.Labelframe1 = LabelFrame(top)
        self.Labelframe1.place(relx=0.07, rely=0.02, relheight=0.14
                , relwidth=0.88)
        self.Labelframe1.configure(relief=RIDGE)
        self.Labelframe1.configure(font=font9)
        self.Labelframe1.configure(foreground="#f39521")
        self.Labelframe1.configure(relief=RIDGE)
        self.Labelframe1.configure(text='''Google Play Music''')
        self.Labelframe1.configure(background="#444444")
        self.Labelframe1.configure(width=530)

        self.Message1 = Message(self.Labelframe1)
        self.Message1.place(relx=0.02, rely=0.20, relheight=0.49, relwidth=0.7)
        self.Message1.configure(background="#444444")
        self.Message1.configure(font=font9)
        self.Message1.configure(foreground="#f39521")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(justify=CENTER)
        self.Message1.configure(text='''Use the JS script to download the playlist as txt''')
        self.Message1.configure(width=372)

        self.Button1 = Button(self.Labelframe1)
        self.Button1.place(relx=0.74, rely=0.07, height=42, width=118)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#f39521")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Download''')
        self.Button1.configure(command=self.google_play_music)
        self.Button1.configure(width=118)

        self.Labelframe2 = LabelFrame(top)
        self.Labelframe2.place(relx=0.07, rely=0.16, relheight=0.14
                , relwidth=0.88)
        self.Labelframe2.configure(relief=RIDGE)
        self.Labelframe2.configure(font=font9)
        self.Labelframe2.configure(foreground="#ff392f")
        self.Labelframe2.configure(relief=RIDGE)
        self.Labelframe2.configure(text='''ToDoist''')
        self.Labelframe2.configure(background="#444444")
        self.Labelframe2.configure(highlightbackground="#d9d9d9")
        self.Labelframe2.configure(highlightcolor="black")
        self.Labelframe2.configure(width=530)

        self.Message2 = Message(self.Labelframe2)
        self.Message2.place(relx=0.02, rely=0.2, relheight=0.49, relwidth=0.7)
        self.Message2.configure(background="#444444")
        self.Message2.configure(font=font9)
        self.Message2.configure(foreground="#ff392f")
        self.Message2.configure(highlightbackground="#d9d9d9")
        self.Message2.configure(highlightcolor="black")
        self.Message2.configure(justify=CENTER)
        self.Message2.configure(text='''Add the song link (Youtube or Soundcloud) to ToDoist Project - Inbox''')
        self.Message2.configure(width=372)

        self.Button2 = Button(self.Labelframe2)
        self.Button2.place(relx=0.74, rely=0.07, height=42, width=118)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#ff392f")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(command=self.todoist)
        self.Button2.configure(text='''Download''')

        self.Labelframe3 = LabelFrame(top)
        self.Labelframe3.place(relx=0.07, rely=0.31, relheight=0.14
                , relwidth=0.88)
        self.Labelframe3.configure(relief=RIDGE)
        self.Labelframe3.configure(font=font9)
        self.Labelframe3.configure(foreground="#ffffff")
        self.Labelframe3.configure(relief=RIDGE)
        self.Labelframe3.configure(text='''Billboard''')
        self.Labelframe3.configure(background="#444444")
        self.Labelframe3.configure(highlightbackground="#d9d9d9")
        self.Labelframe3.configure(highlightcolor="black")
        self.Labelframe3.configure(width=530)

        self.Message3 = Message(self.Labelframe3)
        self.Message3.place(relx=0.04, rely=0.2, relheight=0.49, relwidth=0.32)
        self.Message3.configure(background="#444444")
        self.Message3.configure(font=font9)
        self.Message3.configure(foreground="#ffffff")
        self.Message3.configure(highlightbackground="#d9d9d9")
        self.Message3.configure(highlightcolor="black")
        self.Message3.configure(justify=CENTER)
        self.Message3.configure(text='''Top songs not in iTunes Library''')
        self.Message3.configure(width=172)

        self.Button3 = Button(self.Labelframe3)
        self.Button3.place(relx=0.74, rely=0.07, height=42, width=118)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#ffffff")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(command=self.billboard)
        self.Button3.configure(text='''Download''')

        self.Spinbox1 = Spinbox(self.Labelframe3, from_=1.0, to=100.0)
        self.Spinbox1.place(relx=0.62, rely=0.2, relheight=0.44, relwidth=0.09)
        self.Spinbox1.configure(activebackground="#f9f9f9")
        self.Spinbox1.configure(background="white")
        self.Spinbox1.configure(buttonbackground="#d9d9d9")
        self.Spinbox1.configure(disabledforeground="#a3a3a3")
        self.Spinbox1.configure(font=font13)
        self.Spinbox1.configure(foreground="black")
        self.Spinbox1.configure(from_="25.0")
        self.Spinbox1.configure(highlightbackground="black")
        self.Spinbox1.configure(highlightcolor="black")
        self.Spinbox1.configure(insertbackground="black")
        self.Spinbox1.configure(selectbackground="#c4c4c4")
        self.Spinbox1.configure(selectforeground="black")
        self.Spinbox1.configure(textvariable=GUI_Support.spinbox)
        self.Spinbox1.configure(to="100.0")
        self.Spinbox1.configure(width=48)

        self.Message4 = Message(self.Labelframe3)
        self.Message4.place(relx=0.39, rely=0.2, relheight=0.49, relwidth=0.21)
        self.Message4.configure(background="#444444")
        self.Message4.configure(font=font16)
        self.Message4.configure(foreground="#ffffff")
        self.Message4.configure(highlightbackground="#d9d9d9")
        self.Message4.configure(highlightcolor="black")
        self.Message4.configure(justify=CENTER)
        self.Message4.configure(text='''No. of songs to be downloaded''')
        self.Message4.configure(width=112)

        self.Labelframe4 = LabelFrame(top)
        self.Labelframe4.place(relx=0.07, rely=0.67, relheight=0.3
                , relwidth=0.88)
        self.Labelframe4.configure(relief=RIDGE)
        self.Labelframe4.configure(font=font9)
        self.Labelframe4.configure(foreground="#09bbf7")
        self.Labelframe4.configure(relief=RIDGE)
        self.Labelframe4.configure(text='''Scan and Move files with no AlbumArt''')
        self.Labelframe4.configure(background="#444444")
        self.Labelframe4.configure(highlightbackground="#d9d9d9")
        self.Labelframe4.configure(highlightcolor="black")
        self.Labelframe4.configure(width=530)

        self.Button4 = Button(self.Labelframe4)
        self.Button4.place(relx=0.26, rely=0.6, height=42, width=118)
        self.Button4.configure(activebackground="#d9d9d9")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="#09bbf7")
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(text='''Move''')
        self.Button4.configure(command=self.move_albumart)
        self.Button4.configure(width=188)

        self.Entry1 = Entry(self.Labelframe4)
#        self.Entry1.place(relx=0.28, rely=0.10, relheight=0.13, relwidth=0.44)
        self.Entry1.place(relx=0.28, rely=0.10, height=26, relwidth=0.44)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        READONLY = 'readonly'
        self.Entry1.configure(state=READONLY)
        self.Entry1.configure(textvariable=GUI_Support.scan_folder)
        self.Entry1.configure(width=234)

        self.Button5 = Button(self.Labelframe4)
        self.Button5.place(relx=0.74, rely=0.10, height=26, width=118)
        self.Button5.configure(activebackground="#d9d9d9")
        self.Button5.configure(activeforeground="#000000")
        self.Button5.configure(background="#09bbf7")
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(foreground="#000000")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        self.Button5.configure(pady="0")
        self.Button5.configure(text='''Browse''')
        self.Button5.configure(command=self.folder_pick)
        self.Button5.configure(width=118)

        self.Label1 = Label(self.Labelframe4)
        self.Label1.place(relx=0.04, rely=0.10, height=26, width=120)
        self.Label1.configure(background="#444444")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(anchor=W) 
        self.Label1.configure(text='''Folder to Scan''')

        self.Label2 = Label(self.Labelframe4)
        self.Label2.place(relx=0.04, rely=0.40, height=26, width=300)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#444444")
        self.Label2.configure(anchor=W) 
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#ffffff")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Name of Folder to move the files to''')
        self.Label2.configure(width=300)

        self.Entry2 = Entry(self.Labelframe4)
        self.Entry2.place(relx=0.5, rely=0.40, height=26, relwidth=0.37)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(selectforeground="black")
        self.Entry2.configure(textvariable=GUI_Support.move_folder)
        self.Entry2.configure(width=194)

        self.Labelframe5 = LabelFrame(top)
        self.Labelframe5.place(relx=0.07, rely=0.46, relheight=0.21
                , relwidth=0.88)
        self.Labelframe5.configure(relief=RIDGE)
        self.Labelframe5.configure(font=font9)
        self.Labelframe5.configure(foreground="#caf35c")
        self.Labelframe5.configure(relief=RIDGE)
        self.Labelframe5.configure(text='''Multiple Selections''')
        self.Labelframe5.configure(background="#444444")
        self.Labelframe5.configure(highlightbackground="#d9d9d9")
        self.Labelframe5.configure(highlightcolor="black")
        self.Labelframe5.configure(width=530)

        self.Button6 = Button(self.Labelframe5)
        self.Button6.place(relx=0.74, rely=0.3, height=42, width=118)
        self.Button6.configure(activebackground="#d9d9d9")
        self.Button6.configure(activeforeground="#000000")
        self.Button6.configure(background="#caf35c")
        self.Button6.configure(disabledforeground="#a3a3a3")
        self.Button6.configure(foreground="#000000")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="black")
        self.Button6.configure(pady="0")
        self.Button6.configure(text='''Download''')
        self.Button6.configure(command=self.multiple)

        self.Checkbutton1 = Checkbutton(self.Labelframe5)
        self.Checkbutton1.place(relx=0.09, rely=0.08, relheight=0.26
                , relwidth=0.35)
        self.Checkbutton1.configure(activebackground="#d9d9d9")
        self.Checkbutton1.configure(activeforeground="#000000")
        self.Checkbutton1.configure(anchor=W)
        self.Checkbutton1.configure(background="#444444")
        self.Checkbutton1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1.configure(font=font9)
        self.Checkbutton1.configure(foreground="#f39521")
        self.Checkbutton1.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1.configure(highlightcolor="black")
        self.Checkbutton1.configure(justify=LEFT)
        self.Checkbutton1.configure(text='''Google Play Music''')
        self.Checkbutton1.configure(variable=GUI_Support.gplay)

        self.Checkbutton2 = Checkbutton(self.Labelframe5)
        self.Checkbutton2.place(relx=0.09, rely=0.29, relheight=0.26
                , relwidth=0.35)
        self.Checkbutton2.configure(activebackground="#d9d9d9")
        self.Checkbutton2.configure(activeforeground="#000000")
        self.Checkbutton2.configure(anchor=W)
        self.Checkbutton2.configure(background="#444444")
        self.Checkbutton2.configure(disabledforeground="#a3a3a3")
        self.Checkbutton2.configure(font=font9)
        self.Checkbutton2.configure(foreground="#ff392f")
        self.Checkbutton2.configure(highlightbackground="#d9d9d9")
        self.Checkbutton2.configure(highlightcolor="black")
        self.Checkbutton2.configure(justify=LEFT)
        self.Checkbutton2.configure(text='''ToDoist''')
        self.Checkbutton2.configure(variable=GUI_Support.todoist)

        self.Checkbutton3 = Checkbutton(self.Labelframe5)
        self.Checkbutton3.place(relx=0.09, rely=0.51, relheight=0.26
                , relwidth=0.35)
        self.Checkbutton3.configure(activebackground="#d9d9d9")
        self.Checkbutton3.configure(activeforeground="#000000")
        self.Checkbutton3.configure(anchor=W)
        self.Checkbutton3.configure(background="#444444")
        self.Checkbutton3.configure(disabledforeground="#a3a3a3")
        self.Checkbutton3.configure(font=font9)
        self.Checkbutton3.configure(foreground="#caf35c")
        self.Checkbutton3.configure(highlightbackground="#d9d9d9")
        self.Checkbutton3.configure(highlightcolor="black")
        self.Checkbutton3.configure(justify=LEFT)
        self.Checkbutton3.configure(text='''Billboard''')
        self.Checkbutton3.configure(variable=GUI_Support.bb)



    def google_play_music(self):
        # print "Google"
        GoogleMusicDownload.main()
        
    
    def billboard(self):
        # print "Billboard"
        # print (GUI_Support.spinbox.get())
        Billboard_Chart_Downloader.main(GUI_Support.spinbox.get())
        
    
    def todoist(self):
        # print "Todoist"
        ToDoist.main()
    
    def multiple(self):
        print "Multiple"
        print GUI_Support.gplay.get()
        if GUI_Support.gplay.get()==1:
            self.google_play_music()
        
        if GUI_Support.todoist.get()==1:
            self.todoist()
            
        if GUI_Support.bb.get()==1:
            self.billboard()
        print "end"
        
    
    def move_albumart(self):
        print "Album art"
        no_album_art.main(GUI_Support.scan_folder.get(), GUI_Support.move_folder.get())
    
    def folder_pick(self):
        filename = askdirectory()
        GUI_Support.scan_folder.set(filename)
    




if __name__ == '__main__':
    vp_start_gui()


